apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    # pods: '4' # limit the number of pods to 4
    requests.cpu: "1" # 1000m = 1 CPU
    requests.memory: 1Gi 
    limits.cpu: "2"
    limits.memory: 2Gi
