apiVersion: v1
kind: ConfigMap
metadata:
  name: green-env-vars
data:
  # The color-api app needs this path to set color
  COLOR_CONFIG_PATH: /mnt/config/color.txt

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-files
data:
  color.txt: green
  hello-from-green.js: |
    console.log("Hello from");
    console.log("The green config map");