apiVersion: v1
kind: Pod
metadata:
  name: red-color-api
  labels:
    app: red-color-api
spec:
  containers:
    - name: color-api
      # The below image takes DEFAUTL_COLOR env var.
      image: lmacademy/color-api:1.3.0
      ## One way to define environment variables from a ConfigMap
      # envFrom:
      #   - configMapRef:
      #       name: red-config

      ## Another way to define environment variables from a ConfigMap
      # This will only set the env vars which are required.
      env: 
        - name: DEFAULT_COLOR
          valueFrom:
            configMapKeyRef:
              name: red-config
              key: color
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
