apiVersion: v1
kind: Pod
metadata:
  name: color-api
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    # Note: color-api:1.2.0 is image which has health endpoints
    # also it has purposeful delay of 60 seconds 
    image: lmacademy/color-api:1.2.1
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: "200m"
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: 512Mi
    # Env vars are designed to purposefully fail each of the startup, liveness and readiness probes 
    # to demonstrate the behavior of each probe type
    # Set values to true to see the failure behavior of each probe type
    env:
      - name: DELAY_STARTUP
        value: "false"
      - name: FAIL_LIVENESS
        value: "false"
      - name: FAIL_READINESS
        value: "false"
    startupProbe:
      httpGet:
        path: /up
        port: 80
      failureThreshold: 2
      periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      failureThreshold: 3
      periodSeconds: 10