apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dyanmic-pv-example
spec:
  resources:
    requests:
      storage: 1Gi
      # storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard