apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-deployment
  labels:
    app: color-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-env-COLORDB_USER: "secret/data/k8s_secret#color-api_username"
        vault.hashicorp.com/agent-inject-env-COLORDB_PASS: "secret/data/k8s_secret#color-api_password"
      containers:
        - name: color-api
          image: lmacademy/color-api:1.1.0
          ports: 
            - containerPort: 80